# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # Docker image tag below shall match the openjdk version required in the pom.xml file.
    # List of available images: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:18.0

    # Add steps to the job.
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout

      # Build and run tests.
      - run: mvn --batch-mode test jacoco:report

  deployment:
    docker:
      - image: cimg/openjdk:18.0

    steps:
      - checkout
      - run: mvn --batch-mode deploy --define createDocs=true --settings settings.xml


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
